### ISSUE TITLE
Use of pow with Int exp

### ISSUE THREAD

**Issue by NoahTheDuke** [Aatch/ramp#104]
Is it possible to add a version of Int::pow that accepts another Int as the exponent?

```rust
let n = Int::from(53174392371729765229371175317439237172976522937117);
let new_n = 8 * Int::from(2).pow(n - 1) + 5;
// instead of
let new_n = 8 * (Int::zero()..n).fold(Int::from(2), |acc, _| acc * 2) + 5;
```

Thanks!

**Comment by doomrobo** [comment]
The reasoning for not allowing an `Int` as an exponent is because raising anything to a power that's greater than `usize::MAX` is simply infeasible.

For example, the above code snippet doesn't compile because the integer literal provided to `Int::from` exceeds `usize::MAX`. I changed it to a string and called `from_str_radix`. After about 10min of runtime, the program still hadn't terminated.

Notably, [`pow_mod`](https://docs.rs/ramp/0.4.0/ramp/int/struct.Int.html#method.pow_mod) does support `Int` exponents, because calculating powers with a modulus can be done quite efficiently.

**Comment by NoahTheDuke** [comment]
No worries on the time! Thanks for responding.

The reason I was asking is because I was trying to optimize an implementation of the Ackermann function, well beyond the basic levels, by directly calculating the values of higher `m`s. I'd have to find the old Python code I wrote, but it could do something very similar to my desired code above, because it boxes all numbers and has fancy behind-the-scenes work on handling unbounded numbers.

Thanks for all the hard work on this library!

**Comment by doomrobo** [comment]
Ah ok. I'd like to see the code if you ever find it.

**Comment by NoahTheDuke** [comment]
I seem to have thrown away the Python code, but you can see the Rust code [here](https://github.com/NoahTheDuke/rust_ackermann/blob/master/src/main.rs), very clearly in the `ack_with_struct` formulation, if paired with the [Wiki](https://en.wikipedia.org/wiki/Ackermann_function) page.

In a bit of messing around, I tried implementing the values directly instead of recursively, as shown in the [Wiki Table of Values](https://en.wikipedia.org/wiki/Ackermann_function#Table_of_values), but getting it when `m = 3` or `m = 4` was difficult without being able to pass in an extremely large number. So I just left it out.

**Comment by doomrobo** [comment]
Ah I see. I'm surprised you were able to compute some of these values at all, although I don't really know what exactly is feasible on a modern computer.
