### ISSUE TITLE
Add "ramp-primes" to Documentation

### ISSUE THREAD

**Issue by 0xSilene** [Aatch/ramp#119]
Hi,

I created a library that allows for the generation of random composite, prime, and safe prime numbers in RAMP. I was wondering if you could add it to the documentation. The project is clean and concise and is on crates if you would like to check it out.

Here is the [project link](https://crates.io/crates/ramp-primes)

I hope it can be viewed as an official library as it works darn good.

**Comment by rozbb** [comment]
Thanks for making your crate! As for adding to docs, we don't really have a "recommended dependent crates" section and it would feel weird for me to pick one crate over another. Currently, all but 1 of our [dependent crates](https://crates.io/crates/ramp/reverse_dependencies) do prime number checking and/or generation. Since I don't have the bandwidth right now to go in and audit each one for quality, I'll just have to leave it up to the users.

Closing
