### ISSUE TITLE
usage of `usize`

### ISSUE THREAD

**Issue by vks** [Aatch/ramp#16]
It seems that ramp abuses `usize` as a default unsigned integer in a few places. For example, in `examples/factorial.rs` it makes more sense to use a fixed-size integer (`u32` or `u64`). Also, the operators are usually overloaded for `usize` instead of `u32` or `u64`.

**Comment by Aatch** [comment]
`usize` is defined as being a pointer-sized integer, the only reason `Limb` isn't a wrapper over `usize` is because some of the intrinsics I use are only defined for fixed widths. The overload is because all the operations have much simpler single-word implementations and I know that `usize` won't be larger than a word, while `u64` might. In fact, I overload for `usize` and the "base integer" type (which is either `u32` or `u64`, depending on the platform).

I don't think I rely on the size of `usize` directly, beyond it's definition as being the same as a pointer, but if there is somewhere that isn't true, feel free to point it out and re-open.
